<a href="https://colab.research.google.com/github/MariuszGrecki/Data_science/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy - Intro
NumPy, czyli Numerical Python, to biblioteka programistyczna w języku Python, która dostarcza wsparcie dla efektywnych operacji numerycznych, zwłaszcza na dużych tablicach i macierzach danych. Jest jednym z podstawowych narzędzi w dziedzinie naukowych obliczeń i analizy danych w języku Python.



Główne cechy i funkcje biblioteki NumPy:

**Tablice wielowymiarowe:** NumPy wprowadza nowy typ danych, znany jako "array" (tablica), który pozwala na przechowywanie i operowanie danymi wielowymiarowymi. Tablice w NumPy są bardziej wydajne niż standardowe listy w Pythonie i pozwalają na efektywne wykonywanie operacji matematycznych i statystycznych na danych.

**Efektywne operacje numeryczne:** NumPy dostarcza wiele wbudowanych funkcji i operacji, takich jak dodawanie, mnożenie, podnoszenie do potęgi, funkcje trygonometryczne itp., które działają efektywnie na dużych zbiorach danych.

**Broadcasting:** NumPy umożliwia wykonywanie operacji na tablicach o różnych kształtach, co jest nazywane "broadcasting". Dzięki temu można wygodnie operować na danych o różnych wymiarach, a NumPy automatycznie dostosowuje kształt tablic.

**Indeksowanie i wycinanie:** NumPy oferuje zaawansowane możliwości indeksowania i wycinania danych z tablic, co pozwala na dostęp do konkretnych elementów lub podtablic z dużą precyzją.

**Losowanie liczb:** Biblioteka umożliwia generowanie losowych liczb o różnych rozkładach, co jest przydatne w symulacjach i analizach statystycznych.

**Integracja z innymi bibliotekami:** NumPy jest często używany w połączeniu z innymi bibliotekami do naukowych obliczeń i analizy danych, takimi jak SciPy, pandas, matplotlib i scikit-learn.

**Obsługa danych brakujących:** NumPy ma wbudowane funkcje do pracy z danymi brakującymi, co jest istotne w analizie danych.

**Obsługa danych binarnych:** Możesz używać NumPy do operacji na danych binarnych, takich jak obrazy, dźwięk czy pliki binarne.



NumPy jest nieodzowną biblioteką w ekosystemie naukowych obliczeń w języku Python. Dzięki niej programiści i naukowcy danych mogą wygodnie manipulować dużymi zbiorami danych numerycznych i wykonywać zaawansowane operacje matematyczne. W połączeniu z innymi narzędziami do analizy danych i wizualizacji, NumPy stanowi solidną podstawę dla wielu projektów związanych z naukowymi obliczeniami i analizą danych.

In [ ]:
#Podstawy
import numpy as np
np.__version__

'1.25.2'

In [ ]:
#metody np
#dir(np)

In [ ]:
#help(np.array)

In [ ]:
#wymiary tablic są osiami
# 1D Array

x = np.array([1,3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x) # punkt w przestrzeni R2

numpy.ndarray

In [ ]:
x.ndim #wymiary tablicy

1

In [ ]:
x.shape # kształt

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype # typ danych

dtype('int64')

In [ ]:
y = np.array([1.3, 2.3, 1.4])
y

array([1.3, 2.3, 1.4])

In [ ]:
y.dtype

dtype('float64')

In [ ]:
# 2D array dwuwymiarome tablice postać macierzy
x = np.array([[1,2 , 5], [-3, 1, 8]])
x

array([[ 1,  2,  5],
       [-3,  1,  8]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 3)

In [ ]:
# 3d Array

In [ ]:
x = np.array(
  [
      [
          [4,3,1], [3,1,2]
      ],
      [
          [4,1,3], [4,2,1]
      ],
      [
          [3,2,1], [4,3,2]
      ]
  ]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape # 3 tablice, 2 wiersze, 3 kolumny

(3, 2, 3)

**Podstawowe typy danych**

In [ ]:
#liczby całkowite int64
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [ ]:
#liczby zmiennoprzecikowe float64
A = np.array([1.4,2.45,3.12])
A.dtype

dtype('float64')

In [ ]:
A = np.array([1,2,3], dtype='float') # typ zostanie ustawiony na float
A.dtype

dtype('float64')

In [ ]:
A = np.array([1,2,3], dtype='complex') # typ zostanie ustawiony na complex - liczby złożone
A.dtype

dtype('complex128')

In [ ]:
A = np.array([1.4,2.45,3.12], dtype='int') #nie zaokrągla
A.dtype
A

array([1, 2, 3])

In [ ]:
#wartośc logiczna

A = np.array([True, False])
A.dtype
A

array([ True, False])

In [ ]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

<ipython-input-36-27ab11b0e872>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 230 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  A = np.array([24, 120, 230], dtype=np.int8)


dtype('int8')

In [ ]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')